# Redis connection URL.
redis_url = "redis://127.0.0.1:6379/0"

[telegram]
# Telegram token as obtained from @BotFather
token = "0123456789:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX"

# Receive updates via webhook on specified host.
# More info: https://core.telegram.org/bots/api#getting-updates
# Omit to use long polling.
webhook_host = "guardian.example.com"

# Address on which bot accepts requests from Telegram via webhook.
# Required if `webhook_host` is set. Not used with long polling.
webhook_addr = "127.0.0.1:7878"

[guardian]
## All timeouts are in seconds.

# Delete CAPTCHA messages after timeout.
captcha_expire = 60

# Delete service messages ("Welcome", "Incorrect answer", etc.) after timeout.
message_expire = 10

# Don't show CAPTCHA for ignored users.
# User becomes ignored right after CAPTCHA is shown.
ignore_expire = 300
